# Generated by Django 4.1.1 on 2022-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('nextLevelExp', models.IntegerField(default=100)),
                ('currentExp', models.IntegerField(default=0)),
                ('maxHealth', models.IntegerField(default=0)),
                ('currentHealth', models.IntegerField(default=0)),
                ('maxMana', models.IntegerField(default=0)),
                ('currentMana', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
    ]
