# Generated by Django 4.1.1 on 2022-09-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created']},
        ),
    ]
