export const characters =[
    {
        id: 1,
        name : "John",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
    {
        id: 2,
        name : "Paul",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
    {
        id: 3,
        name : "George",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
    {
        id: 4,
        name : "Ringo",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
]