export default [
    {
        id: number  = 1,
        name: string =  "John",
        level: number = 1,
        nextLevelExp: number = 100,
        currentExp: number = 0,
        maxHealth: number = 10,
        currentHealth: number = 10,
        maxMana: number = 10,
        currentMana: number = 10, 
        attack: number = 10,
        defense: number = 0,
    },
    {
        id: 2,
        name : "Paul",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
    {
        id: 3,
        name : "George",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
    {
        id: 4,
        name : "Ringo",
        level : 1,
        nextLevelExp : 100,
        currentExp : 0,
        maxHealth : 10,
        currentHealth : 10,
        maxMana : 10,
        currentMana : 10, 
        attack : 10,
        defense : 0,
    },
]